spring:
  application:
    name: javacourse
  mvc:
    # To avoid the error when no handler found
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # To avoid the error when no handler found
      add-mappings: false
server:
  port: 8000